{% set version = "0.2.4" %}
{% set name = "knit" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/k/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f94193d93bc785c2603c110cde98a2bb5c89b9124d6d9e9bf0cd9be680b9bbc2

build:
  number: 1002
  skip: True  # [not linux]

requirements:
    host:
        - python
        - setuptools
        - maven
        - openjdk
    run:
        - python
        - requests
        - py4j

test:
  imports:
    - knit

about:
  home: https://github.com/dask/knit
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface YARN

extra:
  recipe-maintainers:
    - quasiben
    - martindurant
    - jcrist
