appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rxwlsAr70eFeK5O6XRIu3Ui6P+ettNHErau0WgdQPJIlZa/Vq70QfNL3YjkxBIpVUMZmQPwhL9rcKh1yjqoji09pPDit6jeN4WHTQdOtsmwz1YhatghSsR47PHRqi1UAo2oV6NYhMI768B7hmnGcb4NwGWTit64mH8sp5s0DoDkDmj6Q/dgdHC1m7/K7dl4U84Ao5MDKXEGaSlcnu+vKC7fJkFUSY66/OIBSXvN6YNauEuNGwTcmcPM4VcvcFvokJ/SpbN4Tr1PfYQSZGvlmGnqpXrCCHaampHHlz7a+qMXBiErPQt8pChBVyH9hLk7GKge1wMo1sWmV4pCnwopBKT0RsbPJKRKHmhZ6G+98oLMaHm/eb4U4w5M5eN3LHTW+IP7SwTzp+uCkpGBgJiJ1X1wQFKcexnX/5lCCr72NHcMXS+JgMdBPF/o/2S83FRwQEjDrIuT0DQXuXLY9KS6LuYbUD7Xdb32N8MUculpU/KZWfa3Iodmku1ExvXT+jTRoTR3yfSXgVRtw9/M7v3NFUQ/R/QA5tWkGJRQqWL8Lr/DjqkY1WvBl51SI22848r562px5s/wzPyg0ZqVWu+YN4yxSiAHg2V7cvo50L/BQG3Bcp1g982SJJ9ucuLkFgnBL6KTVzX3UKHD3ogKMUvEGY75V+bMCIAGQzvnfafFVHJ4=}
conda_forge_output_validation: true
